"""create_stock_indicators_table

Revision ID: 140818f9114a
Revises: 9a8f8eb6b901
Create Date: 2026-02-09 17:19:26.402478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '140818f9114a'
down_revision: Union[str, Sequence[str], None] = '9a8f8eb6b901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sma9_rsi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wma45_rsi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ema45_rsi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sma9_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('the_number', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stamp', sa.Boolean(), nullable=True),
    sa.Column('stamp_daily', sa.Boolean(), nullable=True),
    sa.Column('stamp_weekly', sa.Boolean(), nullable=True),
    sa.Column('rsi_55_70', sa.Boolean(), nullable=True),
    sa.Column('sma9_gt_tn_daily', sa.Boolean(), nullable=True),
    sa.Column('rsi_lt_80_d', sa.Boolean(), nullable=True),
    sa.Column('sma9_rsi_lte_75_d', sa.Boolean(), nullable=True),
    sa.Column('ema45_rsi_lte_70_d', sa.Boolean(), nullable=True),
    sa.Column('rsi_gt_wma45_d', sa.Boolean(), nullable=True),
    sa.Column('sma9rsi_gt_wma45rsi_d', sa.Boolean(), nullable=True),
    sa.Column('sma9_gt_tn_weekly', sa.Boolean(), nullable=True),
    sa.Column('rsi_lt_80_w', sa.Boolean(), nullable=True),
    sa.Column('sma9_rsi_lte_75_w', sa.Boolean(), nullable=True),
    sa.Column('ema45_rsi_lte_70_w', sa.Boolean(), nullable=True),
    sa.Column('rsi_gt_wma45_w', sa.Boolean(), nullable=True),
    sa.Column('sma9rsi_gt_wma45rsi_w', sa.Boolean(), nullable=True),
    sa.Column('rsi_w', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sma9_rsi_w', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wma45_rsi_w', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ema45_rsi_w', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sma9_close_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('the_number_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cci', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cci_ema20', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aroon_up', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aroon_down', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend_signal', sa.Boolean(), nullable=True),
    sa.Column('final_signal', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uix_stock_indicators_symbol_date')
    )
    op.create_index('idx_stock_indicators_date', 'stock_indicators', ['date'], unique=False)
    op.create_index('idx_stock_indicators_final_signal', 'stock_indicators', ['final_signal'], unique=False)
    op.create_index('idx_stock_indicators_score', 'stock_indicators', ['score'], unique=False)
    op.create_index('idx_stock_indicators_symbol', 'stock_indicators', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_indicators_id'), 'stock_indicators', ['id'], unique=False)
    op.drop_table('calculation_checkpoint')
    op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    op.drop_index('ix_prices_industry_group', table_name='prices')
    op.drop_index('ix_prices_sector', table_name='prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_prices_sector', 'prices', ['sector'], unique=False)
    op.create_index('ix_prices_industry_group', 'prices', ['industry_group'], unique=False)
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    op.create_table('calculation_checkpoint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculation_checkpoint_pkey')
    )
    op.drop_index(op.f('ix_stock_indicators_id'), table_name='stock_indicators')
    op.drop_index('idx_stock_indicators_symbol', table_name='stock_indicators')
    op.drop_index('idx_stock_indicators_score', table_name='stock_indicators')
    op.drop_index('idx_stock_indicators_final_signal', table_name='stock_indicators')
    op.drop_index('idx_stock_indicators_date', table_name='stock_indicators')
    op.drop_table('stock_indicators')
    # ### end Alembic commands ###
