"""add sector industry hierarchy to prices

Revision ID: 3baf5e798cdd
Revises: daa5c134d954
Create Date: 2026-01-21 23:16:40.609468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3baf5e798cdd'
down_revision: Union[str, Sequence[str], None] = 'daa5c134d954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('prices', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('prices', sa.Column('sub_industry', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'sub_industry')
    op.drop_column('prices', 'industry')
    op.drop_column('prices', 'sector')
    # ### end Alembic commands ###
