"""Add industry group metrics

Revision ID: 435c4faa7110
Revises: f4988e556831
Create Date: 2026-02-08 13:38:58.100815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '435c4faa7110'
down_revision: Union[str, Sequence[str], None] = 'f4988e556831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('period', sa.Enum('ANNUAL', 'Q1', 'Q2', 'Q3', 'Q4', 'UNKNOWN', name='financialperiod'), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('metric_text', sa.String(), nullable=True),
    sa.Column('label_en', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_symbol', 'year', 'period', 'metric_name', name='uix_financial_metric')
    )
    op.create_index(op.f('ix_company_financial_metrics_company_symbol'), 'company_financial_metrics', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_financial_metrics_id'), 'company_financial_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_company_financial_metrics_metric_name'), 'company_financial_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_company_financial_metrics_period'), 'company_financial_metrics', ['period'], unique=False)
    op.create_index(op.f('ix_company_financial_metrics_year'), 'company_financial_metrics', ['year'], unique=False)
    # op.drop_table('calculation_checkpoint')
    # op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    op.add_column('industry_group_history', sa.Column('letter_grade', sa.String(length=5), nullable=True))
    op.add_column('industry_group_history', sa.Column('change_vs_last_week', sa.Integer(), nullable=True))
    op.add_column('industry_group_history', sa.Column('change_vs_3m_ago', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_group_history', 'change_vs_3m_ago')
    op.drop_column('industry_group_history', 'change_vs_last_week')
    op.drop_column('industry_group_history', 'letter_grade')
    # op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    # op.create_table('calculation_checkpoint',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='calculation_checkpoint_pkey')
    # )
    op.drop_index(op.f('ix_company_financial_metrics_year'), table_name='company_financial_metrics')
    op.drop_index(op.f('ix_company_financial_metrics_period'), table_name='company_financial_metrics')
    op.drop_index(op.f('ix_company_financial_metrics_metric_name'), table_name='company_financial_metrics')
    op.drop_index(op.f('ix_company_financial_metrics_id'), table_name='company_financial_metrics')
    op.drop_index(op.f('ix_company_financial_metrics_company_symbol'), table_name='company_financial_metrics')
    op.drop_table('company_financial_metrics')
    # ### end Alembic commands ###
