"""Add users table for authentication

Revision ID: 45602ffe8632
Revises: 
Create Date: 2025-11-24 13:34:57.759276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45602ffe8632'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'technical_indicators' in tables:
        op.drop_table('technical_indicators')
        
    if 'technical_indicator_data' in tables:
        # Drops indexes if table exists
        # Actually dropping table drops indexes, but explicit drop might fail if already gone?
        # Safe to just drop table with CASCADE usually, but SA uses individual drops.
        # Let's inspect indexes.
        # Simply dropping table is cleaner if we can.
        op.drop_table('technical_indicator_data')
    
    # Adding columns securely
    if 'income_statements' in tables:
        cols = [c['name'] for c in inspector.get_columns('income_statements')]
        if 'preferred_stock_dividends' not in cols:
             op.add_column('income_statements', sa.Column('preferred_stock_dividends', sa.Float(), nullable=True))
    
    if 'stock_quotes' in tables:
        cols = [c['name'] for c in inspector.get_columns('stock_quotes')]
        if 'turnover' in cols:
            op.drop_column('stock_quotes', 'turnover')
        if 'rs_score' in cols:
            op.drop_column('stock_quotes', 'rs_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_quotes', sa.Column('rs_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_quotes', sa.Column('turnover', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('income_statements', 'preferred_stock_dividends')
    op.create_table('technical_indicator_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('indicator_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technical_indicator_data_pkey')
    )
    op.create_index('ix_technical_indicator_data_symbol', 'technical_indicator_data', ['symbol'], unique=False)
    op.create_index('ix_technical_indicator_data_indicator_name', 'technical_indicator_data', ['indicator_name'], unique=False)
    op.create_index('ix_technical_indicator_data_date', 'technical_indicator_data', ['date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_overlay', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tinting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technical_indicators_pkey'),
    sa.UniqueConstraint('name', name='technical_indicators_name_key')
    )
    # ### end Alembic commands ###
