"""add_cfg_wma45_columns

Revision ID: 607fb515736b
Revises: f6631427eb40
Create Date: 2026-02-12 10:54:15.829954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607fb515736b'
down_revision: Union[str, Sequence[str], None] = 'f6631427eb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    op.add_column('stock_indicators', sa.Column('cfg_wma45', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('cfg_wma45_w', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_index('idx_stock_indicators_alryan_signal', table_name='stock_indicators')
    op.drop_column('stock_indicators', 'sma9_weekly')
    op.drop_column('stock_indicators', 'sma4_daily')
    op.drop_column('stock_indicators', 'aroon_logic')
    op.drop_column('stock_indicators', 'price_gt_sma18_daily')
    op.drop_column('stock_indicators', 'cci_cond_daily')
    op.drop_column('stock_indicators', 'sma18_daily')
    op.drop_column('stock_indicators', 'rsi_screener_final_signal')
    op.drop_column('stock_indicators', 'sma18_weekly')
    op.drop_column('stock_indicators', 'sma4_weekly')
    op.drop_column('stock_indicators', 'sma9_daily')
    op.drop_column('stock_indicators', 'alryan_final_signal')
    op.drop_column('stock_indicators', 'cci_cond_weekly')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_indicators', sa.Column('cci_cond_weekly', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('alryan_final_signal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('sma9_daily', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('sma4_weekly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('sma18_weekly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('rsi_screener_final_signal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('sma18_daily', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('cci_cond_daily', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('price_gt_sma18_daily', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('aroon_logic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('sma4_daily', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('sma9_weekly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.create_index('idx_stock_indicators_alryan_signal', 'stock_indicators', ['alryan_final_signal'], unique=False)
    op.drop_column('stock_indicators', 'cfg_wma45_w')
    op.drop_column('stock_indicators', 'cfg_wma45')
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    # ### end Alembic commands ###
