"""Add contact and admin

Revision ID: 822c28a906d9
Revises: 45602ffe8632
Create Date: 2025-11-26 19:46:00.697195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822c28a906d9'
down_revision: Union[str, Sequence[str], None] = '45602ffe8632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'contact_messages' not in tables:
        op.create_table('contact_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
        op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    
    # Safe drop
    if 'technical_indicators' in tables:
        op.drop_table('technical_indicators')
        
    if 'technical_indicator_data' in tables:
        # Drops indexes if table exists
        op.drop_table('technical_indicator_data')
    
    # Safe add columns to users
    if 'users' in tables:
        cols = [c['name'] for c in inspector.get_columns('users')]
        if 'is_verified' not in cols:
             op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
        if 'is_admin' not in cols:
             op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_verified')
    op.create_table('technical_indicator_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('indicator_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technical_indicator_data_pkey')
    )
    op.create_index('ix_technical_indicator_data_symbol', 'technical_indicator_data', ['symbol'], unique=False)
    op.create_index('ix_technical_indicator_data_indicator_name', 'technical_indicator_data', ['indicator_name'], unique=False)
    op.create_index('ix_technical_indicator_data_date', 'technical_indicator_data', ['date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_overlay', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tinting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technical_indicators_pkey'),
    sa.UniqueConstraint('name', name='technical_indicators_name_key')
    )
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
