"""Add technical indicators

Revision ID: 8ba798504be3
Revises: 202601131300
Create Date: 2026-01-21 20:00:18.511194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ba798504be3'
down_revision: Union[str, Sequence[str], None] = '202601131300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('price_minus_sma_10', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('price_minus_sma_21', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('price_minus_sma_50', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('price_minus_sma_150', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('price_minus_sma_200', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('fifty_two_week_high', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('fifty_two_week_low', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('prices', sa.Column('average_volume_50', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'average_volume_50')
    op.drop_column('prices', 'fifty_two_week_low')
    op.drop_column('prices', 'fifty_two_week_high')
    op.drop_column('prices', 'price_minus_sma_200')
    op.drop_column('prices', 'price_minus_sma_150')
    op.drop_column('prices', 'price_minus_sma_50')
    op.drop_column('prices', 'price_minus_sma_21')
    op.drop_column('prices', 'price_minus_sma_10')
    # ### end Alembic commands ###
