"""add_change_vs_6m_ago

Revision ID: 9a8f8eb6b901
Revises: 8571054f5e41
Create Date: 2026-02-08 20:35:52.761193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a8f8eb6b901'
down_revision: Union[str, Sequence[str], None] = '8571054f5e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_group_history', sa.Column('change_vs_6m_ago', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_group_history', 'change_vs_6m_ago')
    # ### end Alembic commands ###
