"""Add SMA 4,9,18 and Alryan Signal columns

Revision ID: 9f704dd01904
Revises: 436e1b914d38
Create Date: 2026-02-12 00:11:56.575947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f704dd01904'
down_revision: Union[str, Sequence[str], None] = '436e1b914d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_checkpoint')
    op.drop_index('ix_company_xbrl_metrics_company_symbol', table_name='company_xbrl_metrics')
    op.drop_index('ix_company_xbrl_metrics_id', table_name='company_xbrl_metrics')
    op.drop_index('ix_company_xbrl_metrics_metric_name', table_name='company_xbrl_metrics')
    op.drop_index('ix_company_xbrl_metrics_period', table_name='company_xbrl_metrics')
    op.drop_index('ix_company_xbrl_metrics_year', table_name='company_xbrl_metrics')
    op.drop_table('company_xbrl_metrics')
    # op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    op.drop_index('ix_prices_industry_group', table_name='prices')
    op.drop_index('ix_prices_sector', table_name='prices')
    op.add_column('stock_indicators', sa.Column('sma4_daily', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma9_daily', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma18_daily', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma4_weekly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma9_weekly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma18_weekly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('price_gt_sma18_daily', sa.Boolean(), nullable=True))
    op.add_column('stock_indicators', sa.Column('cci_cond_daily', sa.Boolean(), nullable=True))
    op.add_column('stock_indicators', sa.Column('cci_cond_weekly', sa.Boolean(), nullable=True))
    op.add_column('stock_indicators', sa.Column('aroon_logic', sa.Boolean(), nullable=True))
    op.add_column('stock_indicators', sa.Column('alryan_final_signal', sa.Boolean(), nullable=True))
    op.alter_column('stock_indicators', 'rsi_14_9days_ago',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_a_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_s9rsi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_e45cfg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_e45rsi',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_e20sma3',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'rsi_14_9days_ago_cfg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'rsi_14_w_shifted',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.drop_index('idx_stock_indicators_cfg_gt_50_daily', table_name='stock_indicators')
    op.create_index('idx_stock_indicators_alryan_signal', 'stock_indicators', ['alryan_final_signal'], unique=False)
    op.drop_column('stock_indicators', 'ema20_sma3_rsi3_w')
    op.drop_column('stock_indicators', 'rsi_w_9_weeks_ago')
    op.drop_column('stock_indicators', 'rsi_14_9_days_ago')
    op.drop_column('stock_indicators', 'e20_sma3_rsi3')
    op.drop_column('stock_indicators', 'e45_cfg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_indicators', sa.Column('e45_cfg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('e20_sma3_rsi3', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('rsi_14_9_days_ago', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('rsi_w_9_weeks_ago', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_indicators', sa.Column('ema20_sma3_rsi3_w', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_index('idx_stock_indicators_alryan_signal', table_name='stock_indicators')
    op.create_index('idx_stock_indicators_cfg_gt_50_daily', 'stock_indicators', ['cfg_gt_50_daily'], unique=False)
    op.alter_column('stock_indicators', 'rsi_14_w_shifted',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'rsi_14_9days_ago_cfg',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_e20sma3',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_e45rsi',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_e45cfg',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_s9rsi',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'stamp_a_value',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('stock_indicators', 'rsi_14_9days_ago',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('stock_indicators', 'alryan_final_signal')
    op.drop_column('stock_indicators', 'aroon_logic')
    op.drop_column('stock_indicators', 'cci_cond_weekly')
    op.drop_column('stock_indicators', 'cci_cond_daily')
    op.drop_column('stock_indicators', 'price_gt_sma18_daily')
    op.drop_column('stock_indicators', 'sma18_weekly')
    op.drop_column('stock_indicators', 'sma9_weekly')
    op.drop_column('stock_indicators', 'sma4_weekly')
    op.drop_column('stock_indicators', 'sma18_daily')
    op.drop_column('stock_indicators', 'sma9_daily')
    op.drop_column('stock_indicators', 'sma4_daily')
    op.create_index('ix_prices_sector', 'prices', ['sector'], unique=False)
    op.create_index('ix_prices_industry_group', 'prices', ['industry_group'], unique=False)
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    op.create_table('company_xbrl_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', postgresql.ENUM('ANNUAL', 'Q1', 'Q2', 'Q3', 'Q4', 'UNKNOWN', name='financialperiod'), autoincrement=False, nullable=True),
    sa.Column('metric_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metric_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_xbrl_metrics_pkey'),
    sa.UniqueConstraint('company_symbol', 'year', 'period', 'metric_name', name='uix_xbrl_metric')
    )
    op.create_index('ix_company_xbrl_metrics_year', 'company_xbrl_metrics', ['year'], unique=False)
    op.create_index('ix_company_xbrl_metrics_period', 'company_xbrl_metrics', ['period'], unique=False)
    op.create_index('ix_company_xbrl_metrics_metric_name', 'company_xbrl_metrics', ['metric_name'], unique=False)
    op.create_index('ix_company_xbrl_metrics_id', 'company_xbrl_metrics', ['id'], unique=False)
    op.create_index('ix_company_xbrl_metrics_company_symbol', 'company_xbrl_metrics', ['company_symbol'], unique=False)
    op.create_table('calculation_checkpoint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculation_checkpoint_pkey')
    )
    # ### end Alembic commands ###
