"""Add missing indicator columns

Revision ID: a8190fe95ea6
Revises: 86b9f786c927
Create Date: 2026-02-11 02:31:13.226051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8190fe95ea6'
down_revision: Union[str, Sequence[str], None] = '86b9f786c927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_indicators', sa.Column('wma45_close', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma4', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma18', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('wma45_close_w', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma4_w', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('sma18_w', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_indicators', sa.Column('close_w', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('stock_indicators', 'price_gt_sma18',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'price_gt_sma9_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'sma_trend_daily',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'sma_trend_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'cci_gt_100',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'cci_ema20_gt_0_daily',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'cci_ema20_gt_0_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'aroon_up_gt_70',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('stock_indicators', 'aroon_down_lt_30',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_indicators', 'aroon_down_lt_30',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'aroon_up_gt_70',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'cci_ema20_gt_0_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'cci_ema20_gt_0_daily',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'cci_gt_100',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'sma_trend_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'sma_trend_daily',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'price_gt_sma9_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stock_indicators', 'price_gt_sma18',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('stock_indicators', 'close_w')
    op.drop_column('stock_indicators', 'sma18_w')
    op.drop_column('stock_indicators', 'sma4_w')
    op.drop_column('stock_indicators', 'wma45_close_w')
    op.drop_column('stock_indicators', 'sma18')
    op.drop_column('stock_indicators', 'sma4')
    op.drop_column('stock_indicators', 'wma45_close')
    op.create_index('ix_prices_sector', 'prices', ['sector'], unique=False)
    op.create_index('ix_prices_industry_group', 'prices', ['industry_group'], unique=False)
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    op.create_table('company_xbrl_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', postgresql.ENUM('ANNUAL', 'Q1', 'Q2', 'Q3', 'Q4', 'UNKNOWN', name='financialperiod'), autoincrement=False, nullable=True),
    sa.Column('metric_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metric_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_xbrl_metrics_pkey'),
    sa.UniqueConstraint('company_symbol', 'year', 'period', 'metric_name', name='uix_xbrl_metric')
    )
    op.create_index('ix_company_xbrl_metrics_year', 'company_xbrl_metrics', ['year'], unique=False)
    op.create_index('ix_company_xbrl_metrics_period', 'company_xbrl_metrics', ['period'], unique=False)
    op.create_index('ix_company_xbrl_metrics_metric_name', 'company_xbrl_metrics', ['metric_name'], unique=False)
    op.create_index('ix_company_xbrl_metrics_id', 'company_xbrl_metrics', ['id'], unique=False)
    op.create_index('ix_company_xbrl_metrics_company_symbol', 'company_xbrl_metrics', ['company_symbol'], unique=False)
    op.create_table('calculation_checkpoint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculation_checkpoint_pkey')
    )
    # ### end Alembic commands ###
