"""add_approval_fields

Revision ID: e5093b7e096c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-07 21:25:44.902644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5093b7e096c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('approval_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['approval_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'approval_token')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'approved_by')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
