"""Add CompanyFinancialMetric table

Revision ID: e8905d5da169
Revises: 140818f9114a
Create Date: 2026-02-10 14:57:30.146287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8905d5da169'
down_revision: Union[str, Sequence[str], None] = '140818f9114a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_checkpoint')
    op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    op.drop_index('ix_prices_industry_group', table_name='prices')
    op.drop_index('ix_prices_sector', table_name='prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_prices_sector', 'prices', ['sector'], unique=False)
    op.create_index('ix_prices_industry_group', 'prices', ['industry_group'], unique=False)
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    op.create_table('calculation_checkpoint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculation_checkpoint_pkey')
    )
    # ### end Alembic commands ###
