"""Add IBD Metrics columns

Revision ID: ec90a03f873d
Revises: 3baf5e798cdd
Create Date: 2026-01-26 22:18:24.075576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec90a03f873d'
down_revision: Union[str, Sequence[str], None] = '3baf5e798cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_technical_indicator_data_date', table_name='technical_indicator_data')
    op.drop_index('ix_technical_indicator_data_indicator_name', table_name='technical_indicator_data')
    op.drop_index('ix_technical_indicator_data_symbol', table_name='technical_indicator_data')
    op.drop_table('technical_indicator_data')
    op.drop_table('technical_indicators')
    op.drop_index('ix_company_profiles_symbol', table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index('ix_stock_quotes_symbol', table_name='stock_quotes')
    op.drop_table('stock_quotes')
    op.drop_table('calculation_checkpoint')
    # op.drop_constraint('companies_symbol_key', 'companies', type_='unique') # Skipped to avoid dependency error
    op.drop_index('idx_prices_symbol_date_new', table_name='prices')
    op.add_column('rs_daily_v2', sa.Column('sector_rs_rating', sa.String(length=5), nullable=True))
    op.add_column('rs_daily_v2', sa.Column('industry_group_rs_rating', sa.String(length=5), nullable=True))
    op.add_column('rs_daily_v2', sa.Column('industry_rs_rating', sa.String(length=5), nullable=True))
    op.add_column('rs_daily_v2', sa.Column('sub_industry_rs_rating', sa.String(length=5), nullable=True))
    op.add_column('rs_daily_v2', sa.Column('acc_dis_rating', sa.String(length=5), nullable=True))
    op.alter_column('rs_daily_v2', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('rs_daily_v2', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('idx_rs_v2_date', table_name='rs_daily_v2')
    op.drop_index('idx_rs_v2_date_rating', table_name='rs_daily_v2')
    op.drop_index('idx_rs_v2_symbol_date', table_name='rs_daily_v2')
    op.drop_constraint('rs_daily_v2_symbol_date_key', 'rs_daily_v2', type_='unique')
    op.create_index('idx_rs_daily_v2_date_rank_12m', 'rs_daily_v2', ['date', sa.text('rank_12m DESC')], unique=False)
    op.create_index('idx_rs_daily_v2_date_rank_3m', 'rs_daily_v2', ['date', sa.text('rank_3m DESC')], unique=False)
    op.create_index('idx_rs_daily_v2_date_rating', 'rs_daily_v2', ['date', sa.text('rs_rating DESC')], unique=False)
    op.create_index('idx_rs_daily_v2_symbol_date', 'rs_daily_v2', ['symbol', 'date'], unique=True)
    op.create_index(op.f('ix_rs_daily_v2_date'), 'rs_daily_v2', ['date'], unique=False)
    op.create_index(op.f('ix_rs_daily_v2_symbol'), 'rs_daily_v2', ['symbol'], unique=False)
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_rs_daily_v2_symbol'), table_name='rs_daily_v2')
    op.drop_index(op.f('ix_rs_daily_v2_date'), table_name='rs_daily_v2')
    op.drop_index('idx_rs_daily_v2_symbol_date', table_name='rs_daily_v2')
    op.drop_index('idx_rs_daily_v2_date_rating', table_name='rs_daily_v2')
    op.drop_index('idx_rs_daily_v2_date_rank_3m', table_name='rs_daily_v2')
    op.drop_index('idx_rs_daily_v2_date_rank_12m', table_name='rs_daily_v2')
    op.create_unique_constraint('rs_daily_v2_symbol_date_key', 'rs_daily_v2', ['symbol', 'date'])
    op.create_index('idx_rs_v2_symbol_date', 'rs_daily_v2', ['symbol', 'date'], unique=False)
    op.create_index('idx_rs_v2_date_rating', 'rs_daily_v2', ['date', sa.text('rs_rating DESC')], unique=False)
    op.create_index('idx_rs_v2_date', 'rs_daily_v2', ['date'], unique=False)
    op.alter_column('rs_daily_v2', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('rs_daily_v2', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('rs_daily_v2', 'acc_dis_rating')
    op.drop_column('rs_daily_v2', 'sub_industry_rs_rating')
    op.drop_column('rs_daily_v2', 'industry_rs_rating')
    op.drop_column('rs_daily_v2', 'industry_group_rs_rating')
    op.drop_column('rs_daily_v2', 'sector_rs_rating')
    op.create_index('idx_prices_symbol_date_new', 'prices', ['symbol', 'date'], unique=False)
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    op.create_table('calculation_checkpoint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calculation_checkpoint_pkey')
    )
    op.create_table('stock_quotes',
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('previous_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percent_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_market_open', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_low_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_high_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_low_change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_high_change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifty_two_week_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('extended_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extended_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extended_percent_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extended_timestamp', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rs_12m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_9m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_6m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_3m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_1m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_2w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_1w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rs_1d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_12m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_9m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_6m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_3m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_1m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_2w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('change_1w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', name='stock_quotes_pkey')
    )
    op.create_index('ix_stock_quotes_symbol', 'stock_quotes', ['symbol'], unique=False)
    op.create_table('company_profiles',
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', name='company_profiles_pkey')
    )
    op.create_index('ix_company_profiles_symbol', 'company_profiles', ['symbol'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_overlay', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tinting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technical_indicators_pkey'),
    sa.UniqueConstraint('name', name='technical_indicators_name_key')
    )
    op.create_table('technical_indicator_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('indicator_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='technical_indicator_data_pkey')
    )
    op.create_index('ix_technical_indicator_data_symbol', 'technical_indicator_data', ['symbol'], unique=False)
    op.create_index('ix_technical_indicator_data_indicator_name', 'technical_indicator_data', ['indicator_name'], unique=False)
    op.create_index('ix_technical_indicator_data_date', 'technical_indicator_data', ['date'], unique=False)
    # ### end Alembic commands ###
