"""add_industry_group_history

Revision ID: f12345678901
Revises: ec90a03f873d
Create Date: 2026-01-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12345678901'
down_revision = 'ec90a03f873d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_group_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry_group', sa.String(length=100), nullable=False),
    sa.Column('number_of_stocks', sa.Integer(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('rs_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_1_week_ago', sa.Integer(), nullable=True),
    sa.Column('rank_3_months_ago', sa.Integer(), nullable=True),
    sa.Column('rank_6_months_ago', sa.Integer(), nullable=True),
    sa.Column('ytd_change_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'industry_group', name='uix_date_industry_group')
    )
    op.create_index(op.f('ix_industry_group_history_date'), 'industry_group_history', ['date'], unique=False)
    op.create_index(op.f('ix_industry_group_history_industry_group'), 'industry_group_history', ['industry_group'], unique=False)
    op.create_index(op.f('ix_industry_group_history_id'), 'industry_group_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industry_group_history_id'), table_name='industry_group_history')
    op.drop_index(op.f('ix_industry_group_history_industry_group'), table_name='industry_group_history')
    op.drop_index(op.f('ix_industry_group_history_date'), table_name='industry_group_history')
    op.drop_table('industry_group_history')
    # ### end Alembic commands ###
