"""add_market_cap_to_prices

Revision ID: f4988e556831
Revises: f12345678901
Create Date: 2026-02-01 13:36:09.999497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4988e556831'
down_revision: Union[str, Sequence[str], None] = 'f12345678901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'market_cap')
    # ### end Alembic commands ###
