"""Add rsi_screener_final_signal column

Revision ID: f6631427eb40
Revises: 9f704dd01904
Create Date: 2026-02-12 00:27:25.484120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6631427eb40'
down_revision: Union[str, Sequence[str], None] = '9f704dd01904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    op.add_column('stock_indicators', sa.Column('rsi_screener_final_signal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_indicators', 'rsi_screener_final_signal')
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    # ### end Alembic commands ###
